version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_next_gemini_development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: rails_next_gemini_development
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["bash", "/app/entrypoint.sh", "rails", "server", "-b", "0.0.0.0"]

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
